name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  biome:
    name: Biome
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup Biome
          uses: biomejs/setup-biome@v2
          with:
            version: latest

        - name: Run Biome
          run: biome ci .

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: pnpm run -r test
